# Image configuration
DOCKER_REGISTRY ?= ghcr.io
DOCKER_REPO ?= agentgateway
IMAGE_NAME ?= agentgateway
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || jj log -r @ -T 'commit_id.shortest(12)' --no-graph 2>/dev/null || echo unknown)
GIT_REVISION ?= $(shell git rev-parse HEAD 2>/dev/null || jj log -r @ -T 'commit_id' --no-graph 2>/dev/null || echo unknown)
IMAGE_TAG ?= $(VERSION)
IMAGE_FULL_NAME ?= $(DOCKER_REGISTRY)/$(DOCKER_REPO)/$(IMAGE_NAME):$(IMAGE_TAG)
DOCKER_BUILDER ?= docker
DOCKER_BUILD_ARGS ?= --build-arg VERSION=$(VERSION) --build-arg GIT_REVISION=$(GIT_REVISION)
DOCKERFILE_S390X ?= Dockerfile.s390x
export PATH := ./tools:$(PATH)

# docker
.PHONY: docker
docker:
ifeq ($(OS),Windows_NT)
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -f Dockerfile.windows -t $(IMAGE_FULL_NAME) .
else
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -t $(IMAGE_FULL_NAME) . --progress=plain
endif

.PHONY: docker-ci
docker-ci:
ifeq ($(OS),Windows_NT)
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) --build-arg PROFILE=ci -f Dockerfile.windows -t $(IMAGE_FULL_NAME) .
else
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) --build-arg PROFILE=ci -t $(IMAGE_FULL_NAME) . --progress=plain
endif

.PHONY: docker-musl
docker-musl:
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -t $(IMAGE_FULL_NAME)-musl --build-arg=BUILDER=musl . --progress=plain

# Build the s390x image from the standalone example Dockerfile.
# NOTE: s390x is NOT an officially supported build architecture; this builds the
# unsupported $(DOCKERFILE_S390X) reference and must be run natively on s390x.
.PHONY: docker-s390x
docker-s390x:
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -f $(DOCKERFILE_S390X) -t $(IMAGE_FULL_NAME)-s390x . --progress=plain

CARGO_BUILD_ARGS ?=

# The web UI is embedded into the binary via the `ui` cargo feature, which
# compiles the built assets from ui/dist into the binary at build time. Those
# assets are generated by the Node/pnpm build and are not checked in, so a plain
# `cargo build --features ui` on a fresh checkout fails.
#
# `make build` rebuilds the UI before embedding it. Set UI=0 to build without the
# embedded UI and skip the Node/pnpm build, which is useful for fast iteration on
# the proxy itself (no Node toolchain required).
UI ?= 1
ifeq ($(UI),0)
UI_PREREQ :=
UI_FEATURE :=
else
UI_PREREQ := ui
UI_FEATURE := --features ui
endif

# `corepack pnpm` needs no `corepack enable`, so this works on a fresh checkout.
.PHONY: ui
ui:
	cd ui && corepack pnpm install --frozen-lockfile && corepack pnpm build

# build
.PHONY: build
build: $(UI_PREREQ)
	cargo build --release $(UI_FEATURE) $(CARGO_BUILD_ARGS)
.PHONY: build-target
build-target: $(UI_PREREQ)
	cargo build $(UI_FEATURE) $(CARGO_BUILD_ARGS) --target $(TARGET) --profile $(PROFILE)

# Build with the SymCrypt provider instead of the default aws-lc-rs. --no-default-features
# also drops jemalloc/mimalloc, which the Linux allocator requires, so they are re-added.
.PHONY: build-symcrypt
build-symcrypt: $(UI_PREREQ)
	cargo build --release --no-default-features --features jemalloc,mimalloc,crypto-symcrypt $(UI_FEATURE) $(CARGO_BUILD_ARGS)

# Build the AWS-LC provider in FIPS mode.
.PHONY: build-fips
build-fips: $(UI_PREREQ)
	cargo build --release --no-default-features --features jemalloc,mimalloc,crypto-aws-lc,fips $(UI_FEATURE) $(CARGO_BUILD_ARGS)

# Build the BoringSSL provider in FIPS mode. BoringSSL's FIPS build requires clang and Go.
BORING_FIPS_FEATURES := jemalloc,mimalloc,crypto-boring,fips
BORING_FIPS_TREE_ARGS := -p agentgateway-app --no-default-features --features $(BORING_FIPS_FEATURES) -e normal,build --target all
.PHONY: build-boring-fips
build-boring-fips: $(UI_PREREQ)
	cargo build --release --no-default-features --features $(BORING_FIPS_FEATURES) $(UI_FEATURE) $(CARGO_BUILD_ARGS)

# Fail if the BoringSSL FIPS build links aws-lc-rs or ring.
.PHONY: check-boring-deps
check-boring-deps:
	@tree=$$(cargo tree --locked $(BORING_FIPS_TREE_ARGS) --prefix none) || exit 1; \
	if echo "$$tree" | grep -E '^(aws-lc[a-z-]*|ring) '; then \
		echo "crypto-boring must not link these. Find the path with: cargo tree -i <crate> $(BORING_FIPS_TREE_ARGS)"; \
		exit 1; \
	fi

# Lint the BoringSSL backend. The non-FIPS build needs no Go.
.PHONY: lint-boring
lint-boring:
	cargo clippy -p agentgateway -p agentgateway-app --all-targets --no-default-features \
		--features agentgateway-app/crypto-boring,agentgateway-app/jemalloc,agentgateway-app/mimalloc \
		-- -D clippy::disallowed_methods -D clippy::disallowed_fields

# lint
.PHONY: lint
lint:
	cargo fmt --check -- --config imports_granularity=Module,group_imports=StdExternalCrate,normalize_comments=true
	cargo clippy --all-targets -- -D clippy::disallowed_methods -D clippy::disallowed_fields

.PHONY: clippy
fix-clippy:
	cargo clippy --fix --allow-staged --allow-dirty --allow-no-vcs

.PHONY: format
format:
	cargo fmt -- --config imports_granularity=Module,group_imports=StdExternalCrate,normalize_comments=true

.PHONY: fix-lint
fix-lint:
	$(MAKE) fix-clippy
	$(MAKE) format

# test
.PHONY: test
test:
	# Unlike --all-targets, these selectors honor test = false on binaries while
	# still covering library/integration tests, examples, and benchmarks.
	cargo test --tests --benches --examples $(if $(TIMINGS),--timings)

.PHONY: test-release
test-release:
	cargo test --profile quick-release --tests --benches --examples $(if $(TIMINGS),--timings)

.PHONY: check-default-members
check-default-members:
	@cargo metadata --no-deps --format-version 1 | jq -e -f tools/check-default-members.jq >/dev/null

# clean
.PHONY: clean
clean:
	cargo clean

objects := $(wildcard examples/*/config.json)

.PHONY: check-clean-repo
check-clean-repo:
	@tools/check_clean_repo.sh

.PHONY: gen
gen: generate-apis generate-schema format
	@:

.PHONY: refresh-model-catalog
refresh-model-catalog:
	go run ./controller/cmd/agctl catalog import --source models.dev,aws-bedrock-mantle --exclude-providers openrouter --overlay ./catalog/model-catalog-overrides.yaml --out ./catalog/model-catalog.json --pretty

.PHONY: generate-schema
generate-schema:
	@cargo xtask schema
	@cargo xtask metrics

# Code generation for xds apis
.PHONY: generate-apis
generate-apis:
	@PATH="./common/tools:$(PATH)" buf generate --path crates/protos/proto/resource.proto --path crates/protos/proto/ext_mcp.proto

.PHONY: run-validation-deps
run-validation-deps:
	@tools/manage-validation-deps.sh start

.PHONY: stop-validation-deps
stop-validation-deps:
	@tools/manage-validation-deps.sh stop

.PHONY: validate
validate:
	@tools/validate-configs.sh
